@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.example.proyectobuscaminas.Inicio_de_juego",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_249303121 { 
   	label=proyectobuscaminas
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   BuscaMinas216037316[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BuscaMinas</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   botones: Button[][] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tablero: int[][] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tiempo: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   turno: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- actualizarNumeros()</TD></TR>
<TR><TD ALIGN="LEFT" >+ contarVacias(fila: int, columna: int): int</TD></TR>
<TR><TD ALIGN="LEFT" >- descubrirCasilla(fila: int, columna: int)</TD></TR>
<TR><TD ALIGN="LEFT" >- encontrarMinas(fila: int, columna: int)</TD></TR>
<TR><TD ALIGN="LEFT" >- generarMinas()</TD></TR>
<TR><TD ALIGN="LEFT" >+ start(primaryStage: Stage)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Dummy216037316[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Dummy</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   botones: Button[][] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tablero: int[][] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tiempo: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   turno: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- actualizarNumeros()</TD></TR>
<TR><TD ALIGN="LEFT" >+ contarVacias(fila: int, columna: int): int</TD></TR>
<TR><TD ALIGN="LEFT" >- descubrirCasilla(fila: int, columna: int)</TD></TR>
<TR><TD ALIGN="LEFT" >- encontrarMinas(fila: int, columna: int)</TD></TR>
<TR><TD ALIGN="LEFT" >- generarMinas()</TD></TR>
<TR><TD ALIGN="LEFT" >+ start(primaryStage: Stage)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Inicio_de_juego216037316[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Inicio_de_juego</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
<TR><TD ALIGN="LEFT" >+ start(primaryStage: Stage)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SeleccionJuego216037316[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SeleccionJuego</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ start(primaryStage: Stage)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Solitario216037316[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Solitario</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   botones: Button[][] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tablero: int[][] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tiempo: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- actualizarNumeros()</TD></TR>
<TR><TD ALIGN="LEFT" >- descubrirCasilla(fila: int, columna: int)</TD></TR>
<TR><TD ALIGN="LEFT" >- generarMinas()</TD></TR>
<TR><TD ALIGN="LEFT" >+ start(primaryStage: Stage)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Tutorial216037316[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Tutorial</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ start(primaryStage: Stage)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Inicio_de_juego216037316 -> SeleccionJuego216037316[label="start() -> start()"];
Inicio_de_juego216037316 -> Tutorial216037316[label="start() -> start()"];
SeleccionJuego216037316 -> BuscaMinas216037316[label="start() -> start()"];
SeleccionJuego216037316 -> Dummy216037316[label="start() -> start()"];
SeleccionJuego216037316 -> Solitario216037316[label="start() -> start()"];
    
}
@enduml